<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121122120439 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE username ADD generated_username VARCHAR(255) NOT NULL");
        $this->addSql("UPDATE username SET generated_username = CONCAT(initials, sequence)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_F85E0677B8FF31CE ON username (generated_username)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP INDEX UNIQ_F85E0677B8FF31CE ON username");
        $this->addSql("ALTER TABLE username DROP generated_username");
    }
}
