<?php

namespace Ice\UsernameGeneratorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsernameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsernameRepository extends EntityRepository
{
    public function findCurrentSequenceForInitials($initials)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('MAX(u.sequence)')
            ->where('u.initials = :initials')
            ->setParameter('initials', $initials);

        $query = $qb->getQuery();

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
